"""move hls data to media model

Revision ID: 9aaac94ab48e
Revises: abdc31a2264b
Create Date: 2025-12-17 10:41:00.809424

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '9aaac94ab48e'
down_revision: Union[str, Sequence[str], None] = 'abdc31a2264b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('MEDIA_META_DATA', sa.Column('master_file', sa.Boolean(), nullable=False))
    op.add_column('MEDIA_META_DATA', sa.Column('video_tracks', sa.JSON(), nullable=False))
    op.add_column('MEDIA_META_DATA', sa.Column('audio_tracks', sa.JSON(), nullable=False))
    op.add_column('MEDIA_META_DATA', sa.Column('subtitle_tracks', sa.JSON(), nullable=False))
    op.add_column('MEDIA_META_DATA', sa.Column('thumbnail', sa.Boolean(), nullable=False))
    op.drop_column('VIDEO_META_DATA', 'thumbnail')
    op.drop_column('VIDEO_META_DATA', 'audio_tracks')
    op.drop_column('VIDEO_META_DATA', 'language')
    op.drop_column('VIDEO_META_DATA', 'video_tracks')
    op.drop_column('VIDEO_META_DATA', 'master_file')
    op.drop_column('VIDEO_META_DATA', 'subtitle_tracks')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('VIDEO_META_DATA', sa.Column('subtitle_tracks', mysql.JSON(), nullable=False))
    op.add_column('VIDEO_META_DATA', sa.Column('master_file', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
    op.add_column('VIDEO_META_DATA', sa.Column('video_tracks', mysql.JSON(), nullable=False))
    op.add_column('VIDEO_META_DATA', sa.Column('language', mysql.VARCHAR(length=256), nullable=False))
    op.add_column('VIDEO_META_DATA', sa.Column('audio_tracks', mysql.JSON(), nullable=False))
    op.add_column('VIDEO_META_DATA', sa.Column('thumbnail', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
    op.drop_column('MEDIA_META_DATA', 'thumbnail')
    op.drop_column('MEDIA_META_DATA', 'subtitle_tracks')
    op.drop_column('MEDIA_META_DATA', 'audio_tracks')
    op.drop_column('MEDIA_META_DATA', 'video_tracks')
    op.drop_column('MEDIA_META_DATA', 'master_file')
    # ### end Alembic commands ###
