"""restructure for hls config tracking

Revision ID: abdc31a2264b
Revises: ccba3927c43b
Create Date: 2025-12-15 09:37:58.850257

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'abdc31a2264b'
down_revision: Union[str, Sequence[str], None] = 'ccba3927c43b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('VIDEO_META_DATA', sa.Column('views', sa.Integer(), nullable=False))
    op.add_column('VIDEO_META_DATA', sa.Column('master_file', sa.Boolean(), nullable=False))
    op.add_column('VIDEO_META_DATA', sa.Column('video_tracks', sa.JSON(), nullable=False))
    op.add_column('VIDEO_META_DATA', sa.Column('audio_tracks', sa.JSON(), nullable=False))
    op.add_column('VIDEO_META_DATA', sa.Column('subtitle_tracks', sa.JSON(), nullable=False))
    op.add_column('VIDEO_META_DATA', sa.Column('thumbnail', sa.Boolean(), nullable=False))
    op.alter_column('VIDEO_META_DATA', 'description',
               existing_type=mysql.VARCHAR(length=512),
               type_=sa.String(length=1024),
               existing_nullable=False)
    op.drop_column('VIDEO_META_DATA', 'screen_height')
    op.drop_column('VIDEO_META_DATA', 'file_path')
    op.drop_column('VIDEO_META_DATA', 'screen_width')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('VIDEO_META_DATA', sa.Column('screen_width', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('VIDEO_META_DATA', sa.Column('file_path', mysql.VARCHAR(length=256), nullable=False))
    op.add_column('VIDEO_META_DATA', sa.Column('screen_height', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.alter_column('VIDEO_META_DATA', 'description',
               existing_type=sa.String(length=1024),
               type_=mysql.VARCHAR(length=512),
               existing_nullable=False)
    op.drop_column('VIDEO_META_DATA', 'thumbnail')
    op.drop_column('VIDEO_META_DATA', 'subtitle_tracks')
    op.drop_column('VIDEO_META_DATA', 'audio_tracks')
    op.drop_column('VIDEO_META_DATA', 'video_tracks')
    op.drop_column('VIDEO_META_DATA', 'master_file')
    op.drop_column('VIDEO_META_DATA', 'views')
    # ### end Alembic commands ###
