"""optional media id

Revision ID: ca8334bd3faf
Revises: 993a0a433094
Create Date: 2025-12-04 09:14:40.213687

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'ca8334bd3faf'
down_revision: Union[str, Sequence[str], None] = '993a0a433094'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('MEDIA_TASK', 'media_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.drop_constraint(op.f('MEDIA_TASK_ibfk_1'), 'MEDIA_TASK', type_='foreignkey')
    op.create_foreign_key(None, 'MEDIA_TASK', 'MEDIA_META_DATA', ['media_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'MEDIA_TASK', type_='foreignkey')
    op.create_foreign_key(op.f('MEDIA_TASK_ibfk_1'), 'MEDIA_TASK', 'MEDIA_META_DATA', ['media_id'], ['id'])
    op.alter_column('MEDIA_TASK', 'media_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
