"""updating to current db models

Revision ID: ccba3927c43b
Revises: ca8334bd3faf
Create Date: 2025-12-06 07:58:10.607470

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ccba3927c43b'
down_revision: Union[str, Sequence[str], None] = 'ca8334bd3faf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'VIDEO_META_DATA', 'MEDIA_META_DATA', ['media_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'VIDEO_META_DATA', type_='foreignkey')
    # ### end Alembic commands ###
